#-------------------------------
# General Site Settings

logo: '/assets/img/musa-logo.png'

intro_title: Spatial data enthusiast | MUSA @ University of Pennsylvania (May 2026) | B.Sc. Geography, UCL
intro_text: |
  Passionate about agent-based modeling for transportation forecasting, disaster behavior simulation, and multimodal AI in geographic analysis.

  Currently collaborating with Henning Larsen on an urban data taxonomy project, helping designers better access and leverage data in architectural practice. Previously at Hisense Cold Chain, supporting sales teams through data management and visualization.
  
resume: '/resume'
resume_link_title: View CV

menu:
- {name: 'Projects', url: ' '}
- {name: 'Experience', url: 'experience'}
- {name: 'Blog and Creation',     url: 'blog'}
- {name: 'About',    url: 'about'}

#-------------------------------
# Contact Section

social_label: Connect
social:
- {icon: 'github',   link: 'https://github.com/lluluciano0505'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jingqi-lu-04a910266'}
- {icon: 'envelope', link: 'mailto:lluluciano0505@gmail.com'}

#-------------------------------
# SEO Section

seo:
  description: 'Jingqi Lu | MUSA Student at UPenn | Spatial Data, AI Agent Modelling, Mobility & Spatial Justice'
  rel-author: ''
  rel-publisher: ''

#-------------------------------
# Google Analytics Section

google-analytics-ua: ''

#-------------------------------
# Disqus Section

disqus:
  comments: false
  disqus_shortname: ''